/**
 * Generates the OCR of every Catena Aurea scan part in CATENA_SCANS
 * (issue #85).
 *
 * Runs ocr/rapidocr_pages.py in the pinned uv environment against each
 * part's checksum-accepted JP2 bundle and writes data/texts/catena/ocr/
 * <item>.rapidocr.json. The document records the bundle checksum, the
 * package versions, the model checksums and the configuration that produced
 * it, and the checksum of the script, so a present document is regenerated
 * when any of those changed; a document holding only some of the bundle's
 * leaves (a --leaves diagnosis) is never current.
 *
 * Run from packages/data-pipeline:
 *   pnpm run ocr:catena            every part, skipping current documents
 *   pnpm run ocr:catena -- --force regenerate them all
 */

import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { dataDir } from './core/paths.js';
import { sha256File } from './core/checksums.js';
import { SOURCE_CHECKSUMS } from './core/source-checksums.js';
import { CATENA_SCANS, scanSourceFile, scanSourceKey, scanOcrFile } from './import-catena-aurea.js';
import { rapidOcrProblem, type RapidOcrDocument } from './importers/rapidocr-json.js';

const textsDir = path.join(dataDir, 'texts', 'catena');
const ocrProject = path.resolve(import.meta.dirname, '..', 'ocr');
const FORCE = process.argv.includes('--force');

/** The environment as installed: versions and model checksums, read the same way the script records them. */
function environment(): { engine: Record<string, string>; models: Record<string, string> } {
    const probe = spawnSync('uv', ['run', '--frozen', '--project', ocrProject, 'python', '-c', `
import json, hashlib, os, platform, sys
from importlib.metadata import version
import rapidocr_onnxruntime
base = os.path.dirname(rapidocr_onnxruntime.__file__)
models = {}
for root, _, files in os.walk(base):
    for f in sorted(files):
        if f.endswith('.onnx') or f == 'config.yaml':
            p = os.path.join(root, f); models[os.path.relpath(p, base)] = hashlib.sha256(open(p, 'rb').read()).hexdigest()
print(json.dumps({'engine': {'python': platform.python_version(), 'rapidocr_onnxruntime': version('rapidocr-onnxruntime'), 'onnxruntime': version('onnxruntime'), 'pillow': version('pillow'), 'numpy': version('numpy')}, 'models': dict(sorted(models.items()))}))
`], { encoding: 'utf-8' });
    if (probe.status !== 0) throw new Error(`[ocr:catena] cannot probe the OCR environment (is uv installed?):\n${probe.stderr}`);
    return JSON.parse(probe.stdout) as { engine: Record<string, string>; models: Record<string, string> };
}

// The generator's own checksum and default configuration: a change to either makes every document stale
const generator = path.join(ocrProject, 'rapidocr_pages.py');
const generatorSha256 = sha256File(generator);
const printed = spawnSync('uv', ['run', '--frozen', '--project', ocrProject, 'python', generator, '--print-config'], { encoding: 'utf-8' });
if (printed.status !== 0) throw new Error(`[ocr:catena] cannot read the generator's configuration:\n${printed.stderr}`);
const defaultConfig = JSON.parse(printed.stdout) as Record<string, unknown>;
// Key order is the script's, not part of the configuration
const canonical = (v: unknown): string => JSON.stringify(v, (_k, x) => (x && typeof x === 'object' && !Array.isArray(x) ? Object.fromEntries(Object.entries(x).sort(([a], [b]) => a.localeCompare(b))) : x));

const env = environment();
for (const scan of CATENA_SCANS) {
    const bundle = path.join(textsDir, 'source', scanSourceFile(scan));
    if (!fs.existsSync(bundle)) throw new Error(`[ocr:catena] Missing ${bundle} - run fetch:catena`);
    const accepted = SOURCE_CHECKSUMS[scanSourceKey(scan)]?.sha256;
    const out = path.join(textsDir, scanOcrFile(scan));
    if (!FORCE && fs.existsSync(out)) {
        const doc = JSON.parse(fs.readFileSync(out, 'utf-8')) as RapidOcrDocument;
        const stale = rapidOcrProblem(doc, scan.item, accepted)
            ?? (canonical(doc.engine) !== canonical(env.engine) ? 'package versions changed' : null)
            ?? (canonical(doc.models) !== canonical(env.models) ? 'models changed' : null)
            ?? (doc.generator?.sha256 !== generatorSha256 ? 'generated by another version of rapidocr_pages.py' : null)
            ?? (canonical(doc.config) !== canonical(defaultConfig) ? 'generated with another configuration' : null);
        if (!stale) { console.log(`[ocr:catena] ${scan.item}: current (${doc.pages.length} pages)`); continue; }
        console.log(`[ocr:catena] ${scan.item}: stale (${stale}), regenerating`);
    }
    const run = spawnSync('uv', ['run', '--frozen', '--project', ocrProject, 'python', path.join(ocrProject, 'rapidocr_pages.py'), '--zip', bundle, '--out', out], { stdio: 'inherit' });
    if (run.status !== 0) throw new Error(`[ocr:catena] ${scan.item}: OCR failed`);
    const doc = JSON.parse(fs.readFileSync(out, 'utf-8')) as RapidOcrDocument;
    const problem = rapidOcrProblem(doc, scan.item, accepted);
    if (problem) throw new Error(`[ocr:catena] ${out}: ${problem}`);
}
